### ISSUE TITLE
How to configuration to  automatically update the database table?

### ISSUE THREAD

**Issue by geekyzk** [DevExpress/XPO#41]
Hi team:
   When i use https://github.com/DevExpress/XPO/tree/master/Tutorials/ASP.NET/MVC.RazorPages/  demo.
   if use DemoDataHelper.seed init model data,  the model table will auto create. 
   if not use DemoDataHelper.seed, the model table not auto create.
   How to configuration to  automatically update the database table?

**Comment by Uriahas** [comment]
Hi,

XPO supports different auto creation modes. Please check this article for details: [AutoCreateOption Enum](https://docs.devexpress.com/CoreLibraries/DevExpress.Xpo.DB.AutoCreateOption).

If this information does not help, feel free to submit a ticket in our [Support Center](https://supportcenter.devexpress.com/). We will be happy to help you.
