### ISSUE TITLE
Doesn't show any data.

### ISSUE THREAD

**Issue by PETERHUP** [DevExpress/XPO#60]
When I run this sample, both DxDataGrids comes up blank.  The XPO data does not get retrieved in the sample app or it isn't working with the Grid. 

![2021-04-25_16-38-28](https://user-images.githubusercontent.com/2748071/116012031-5067b600-a5e5-11eb-8ccc-7460084d606d.jpg)

**Comment by Uriahas** [comment]
Hi!

Please accept my apologies for the delayed response. For technical assistance on this issue, please submit a ticket in our Support Center: https://supportcenter.devexpress.com/ticket/list.
